# ----------------------------------------
# Basic site settings
# ----------------------------------------
remote_theme: raviriley/agency-jekyll-theme

url       : "https://www.flinthillstenantsunited.org"
baseurl   : ""                 # leave empty for root‐domain site

title       : "Flint Hills Tenants United"
#email       : ""
description : "Official website for Flint HIlls Tenants United"
author      : "Derron Borders"

logo:
  path  : "/assets/img/fhtulogo.png"
  height: 60

locale: "en-US"


# ----------------------------------------
# Collections
# ----------------------------------------
collections:
  portfolio:
    output: true




# ----------------------------------------
# Markdown processor
# ----------------------------------------
markdown: kramdown


# ----------------------------------------
# Plugins (GitHub Pages–allowed only)
# ----------------------------------------
plugins:
  - jekyll-remote-theme



formspree_form_path: "f/xrbllpoy"
